language: ruby
rvm:
- 2.1.0
- 2.0.0
script:
- bundle exec rspec spec/
bundler_args: --binstubs=./bundler_stubs
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: gAmJljRYi4Q856xuMD8WEKzL/BCe1U64ysKLVaNJG0kStfbhdNlCKe9BNmAtRa1ux6/9sA5FA+rLMk6ydx9tGL4+w8J6qWPVseJ/HwsNupN77wy+2JBWXcEF6CybTB73lkVk411qhGc1jhjt7Qj5uRTWu52gwxZDR+x4rnBkcJs=
  - secure: Z9nPj7KjMDZDMP3SyzMv3KO2AEc6OZxmIc+OPJ5WQrQDHqkN9Ur7d48E56PDeKshpdIYygk3xs87lheBDwHVHbZgesTTc05KinCOmJmSLcvE97Lz8CoHMpULDvmQpmyJspnRorTznKbaZ393eaa0q9peZrHkUD2f78IzZvmfmjs=
